# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0df183a2468f8df9dea96b93ee2678a15835b861d1db6f21f1d527c8a00016ed96fa367601bedacdef64414020136420036858cf8f2628a7f7616f65d4bcd76f

test:
  secret_key_base: eb736f650eadd1e39384e9d3ca95a9bfd2930718a5b639a49416208be0c03cbde5650c636bf22592b2eb72e349c696238e58b6d8f368e96277c45e341b7dbb6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
